typography_spectrum: 0.5540093693416566
color:
  brandStrength: 0.6990652293898165
  lightness: 0.04019960737787187
  saturation: 0.8477893276140094
  rhythmicContrast: 0.45417462894693017
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
layout_spectrum: 0.23135804221965373
author:
  name: Christopher Gay
  email: iwiretechnologies@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4142cdac-9ee2-4b2a-b138-c0147ef4fc39.png
name: iwireVISION
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7f8b3cf4-a299-4ee0-a08e-3871695e228b.png
title: Think-a-teria
description: Put on your thinking Cap
